CREATE TABLE MEMBER_TBL_03(
	CUSTNO NUMBER(6) NOT NULL PRIMARY KEY,
	CUSTNAME VARCHAR2(20),
	PHONE VARCHAR2(13),
	ADDRESS VARCHAR2(60),
	JOINDATE DATE,
	GRADE CHAR(1),
	CITY CHAR(2)
);

CREATE SEQUENCE MEM_SEQ_CUSTNO
INCREMENT BY 1
START WITH 100001;

CREATE TABLE MONEY_TBL_03(
	CUSTNO NUMBER(6) NOT NULL,
	SALENO NUMBER(8) NOT NULL,
	PCOST NUMBER(8),
	AMOUNT NUMBER(4),
	PRICE NUMBER(8),
	PCODE VARCHAR2(4),
	SDATE DATE,
	PRIMARY KEY (CUSTNO, SALENO)
);
