SELECT CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY FROM MEMBER_TBL_03;

SELECT MAX(CUSTNO)+1 FROM MEMBER_TBL_03;

SELECT * FROM MEMBER_TBL_03;

SELECT CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY FROM MEMBER_TBL_03 WHERE CUSTNO = ?;

INSERT INTO MEMBER_TBL_03 VALUES(MEM_SEQ_CUSTNO.NEXTVAL, '윤한석', '010-5230-7564', '대구시 대구', SYSDATE, 'A', '22');

UPDATE MEMBER_TBL_03 SET CUSTNAME = ?, PHONE = ?, ADDRESS = ?, JOINDATE = ?, GRADE = ?, CITY = ? WHERE CUSTNO = ?;

DELETE FROM MEMBER_TBL_03 WHERE CUSTNO in (100007, 100008, 100009);

SELECT t.CUSTNO AS CUSTNO, CUSTNAME, GRADE, SUM(PRICE) AS PRICE FROM MEMBER_TBL_03 t JOIN MONEY_TBL_03 m ON t.CUSTNO = m.CUSTNO GROUP BY t.CUSTNO, CUSTNAME, GRADE ORDER BY PRICE DESC;